#
# Schumix Hook
#

# Travis language: cpp
language: cpp

install:
 - sudo apt-get install g++ libssl-dev mysql-client mysql-server libmysql++-dev libmysqlclient-dev libcurl4-gnutls-dev libboost-all-dev

script:
 - ./build.sh

# Only watch the master branch
branches:
  only:
    - master

# Notify if needed
notifications:
  irc:
    channels:
      - "flame.yeahunter.hu#dev"
